<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lib/PHPCfg/Printer/Protobuf/specs.proto

namespace PHPCfg\Printer\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protos.PrimitiveType</code>
 */
class PrimitiveType extends \Google\Protobuf\Internal\Message
{
    protected $value;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $string
     *     @type float $float
     *     @type int $int
     *     @type bool $bool
     * }
     */
    public function __construct($data = NULL) {
        \PHPCfg\Printer\Protobuf\Specs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string string = 1;</code>
     * @return string
     */
    public function getString()
    {
        return $this->readOneof(1);
    }

    public function hasString()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>string string = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setString($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>float float = 2;</code>
     * @return float
     */
    public function getFloat()
    {
        return $this->readOneof(2);
    }

    public function hasFloat()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>float float = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setFloat($var)
    {
        GPBUtil::checkFloat($var);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 int = 3;</code>
     * @return int
     */
    public function getInt()
    {
        return $this->readOneof(3);
    }

    public function hasInt()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>uint32 int = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setInt($var)
    {
        GPBUtil::checkUint32($var);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool bool = 4;</code>
     * @return bool
     */
    public function getBool()
    {
        return $this->readOneof(4);
    }

    public function hasBool()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>bool bool = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setBool($var)
    {
        GPBUtil::checkBool($var);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getValue()
    {
        return $this->whichOneof("value");
    }

}

