<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lib/PHPCfg/Printer/Protobuf/specs.proto

namespace PHPCfg\Printer\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>protos.Script</code>
 */
class Script extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .protos.Script.Function functions = 1;</code>
     */
    private $functions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \PHPCfg\Printer\Protobuf\Script\PBFunction[] $functions
     * }
     */
    public function __construct($data = NULL) {
        \PHPCfg\Printer\Protobuf\Specs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .protos.Script.Function functions = 1;</code>
     * @return RepeatedField<\PHPCfg\Printer\Protobuf\Script\PBFunction>
     */
    public function getFunctions()
    {
        return $this->functions;
    }

    /**
     * Generated from protobuf field <code>repeated .protos.Script.Function functions = 1;</code>
     * @param \PHPCfg\Printer\Protobuf\Script\PBFunction[] $var
     * @return $this
     */
    public function setFunctions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \PHPCfg\Printer\Protobuf\Script\PBFunction::class);
        $this->functions = $arr;

        return $this;
    }

}

