// protoc --proto_path=./ --php_out=./lib/ ./lib/PHPCfg/Printer/Protobuf/specs.proto

syntax = "proto3";

package protos;

option php_namespace = "PHPCfg\\Printer\\Protobuf";
option php_metadata_namespace = "PHPCfg\\Printer\\Protobuf";

message Scalar {
  oneof value {
    string string = 1;
    float float = 2;
    uint32 int = 3;
    bool bool = 4;
  }
}

message Script {
  repeated Function functions = 1;

  message Function {
    repeated Block blocks = 1;
    string name = 2;
    optional string class = 3;
    string returnType = 4;

    message Block {
      repeated Op ops = 1;
      uint32 id = 2;
      repeated uint32 parentIds = 3;
      repeated CatchTarget catchTargets = 4;
      optional FinallyTarget finallyTarget = 5;

      message CatchTarget {
        string type = 1;
        Operand.OneOperand var = 2;
        uint32 blockId = 3;
      }

      message FinallyTarget {
        uint32 blockId = 1;
      }

      message Operand {
        message Null {
        }

        message Literal {
          string type = 1;
          string value = 2;
        }

        message Temporary {
          string type = 1;
          uint32 id = 2;
          optional Variable original = 3;
        }

        message Variable {
          string type = 1;
          string name = 2;
          optional string scope = 3;
          optional bool reference = 4;
        }
        
        message OneOperand {
          oneof value {
            Operand.Null null = 1;
            Operand.Literal literal = 2;
            Operand.Temporary temporary = 3;
            Operand.Variable variable = 4;
          }
        }
      }

      message Op {
        message MapLabel {
          map<string, OneLabelType> value = 1;
        }

        message OneLabelType {
          oneof value {
            MapLabel map = 1;
            Scalar scalar = 2;
            Operand.OneOperand operand = 3;
          }
        }

        string kind = 1;
        MapLabel label = 2;
        map<string, uint32> childBlocks = 3;
      }
    }
  }
}