<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lib/PHPCfg/Printer/Protobuf/specs.proto

namespace PHPCfg\Printer\Protobuf\Script\PBFunction\Block\Operand;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>protos.Script.Function.Block.Operand.OneOperand</code>
 */
class OneOperand extends \Google\Protobuf\Internal\Message
{
    protected $value;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \PHPCfg\Printer\Protobuf\Script\PBFunction\Block\Operand\PBNull $null
     *     @type \PHPCfg\Printer\Protobuf\Script\PBFunction\Block\Operand\Literal $literal
     *     @type \PHPCfg\Printer\Protobuf\Script\PBFunction\Block\Operand\Temporary $temporary
     *     @type \PHPCfg\Printer\Protobuf\Script\PBFunction\Block\Operand\Variable $variable
     * }
     */
    public function __construct($data = NULL) {
        \PHPCfg\Printer\Protobuf\Specs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.protos.Script.Function.Block.Operand.Null null = 1;</code>
     * @return \PHPCfg\Printer\Protobuf\Script\PBFunction\Block\Operand\PBNull|null
     */
    public function getNull()
    {
        return $this->readOneof(1);
    }

    public function hasNull()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.protos.Script.Function.Block.Operand.Null null = 1;</code>
     * @param \PHPCfg\Printer\Protobuf\Script\PBFunction\Block\Operand\PBNull $var
     * @return $this
     */
    public function setNull($var)
    {
        GPBUtil::checkMessage($var, \PHPCfg\Printer\Protobuf\Script\PBFunction\Block\Operand\PBNull::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protos.Script.Function.Block.Operand.Literal literal = 2;</code>
     * @return \PHPCfg\Printer\Protobuf\Script\PBFunction\Block\Operand\Literal|null
     */
    public function getLiteral()
    {
        return $this->readOneof(2);
    }

    public function hasLiteral()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.protos.Script.Function.Block.Operand.Literal literal = 2;</code>
     * @param \PHPCfg\Printer\Protobuf\Script\PBFunction\Block\Operand\Literal $var
     * @return $this
     */
    public function setLiteral($var)
    {
        GPBUtil::checkMessage($var, \PHPCfg\Printer\Protobuf\Script\PBFunction\Block\Operand\Literal::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protos.Script.Function.Block.Operand.Temporary temporary = 3;</code>
     * @return \PHPCfg\Printer\Protobuf\Script\PBFunction\Block\Operand\Temporary|null
     */
    public function getTemporary()
    {
        return $this->readOneof(3);
    }

    public function hasTemporary()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.protos.Script.Function.Block.Operand.Temporary temporary = 3;</code>
     * @param \PHPCfg\Printer\Protobuf\Script\PBFunction\Block\Operand\Temporary $var
     * @return $this
     */
    public function setTemporary($var)
    {
        GPBUtil::checkMessage($var, \PHPCfg\Printer\Protobuf\Script\PBFunction\Block\Operand\Temporary::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protos.Script.Function.Block.Operand.Variable variable = 4;</code>
     * @return \PHPCfg\Printer\Protobuf\Script\PBFunction\Block\Operand\Variable|null
     */
    public function getVariable()
    {
        return $this->readOneof(4);
    }

    public function hasVariable()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.protos.Script.Function.Block.Operand.Variable variable = 4;</code>
     * @param \PHPCfg\Printer\Protobuf\Script\PBFunction\Block\Operand\Variable $var
     * @return $this
     */
    public function setVariable($var)
    {
        GPBUtil::checkMessage($var, \PHPCfg\Printer\Protobuf\Script\PBFunction\Block\Operand\Variable::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getValue()
    {
        return $this->whichOneof("value");
    }

}

