<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lib/PHPCfg/Printer/Protobuf/specs.proto

namespace PHPCfg\Printer\Protobuf\Script\PBFunction\Block;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protos.Script.Function.Block.FinallyTarget</code>
 */
class FinallyTarget extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 blockId = 1;</code>
     */
    protected $blockId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $blockId
     * }
     */
    public function __construct($data = NULL) {
        \PHPCfg\Printer\Protobuf\Specs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 blockId = 1;</code>
     * @return int
     */
    public function getBlockId()
    {
        return $this->blockId;
    }

    /**
     * Generated from protobuf field <code>uint32 blockId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setBlockId($var)
    {
        GPBUtil::checkUint32($var);
        $this->blockId = $var;

        return $this;
    }

}

