<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lib/PHPCfg/Printer/Protobuf/specs.proto

namespace PHPCfg\Printer\Protobuf\Script\PBFunction\Block;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protos.Script.Function.Block.Op</code>
 */
class Op extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.protos.Script.Function.Block.Op.MapLabel label = 1;</code>
     */
    protected $label = null;
    /**
     * Generated from protobuf field <code>map<string, uint32> childBlocks = 2;</code>
     */
    private $childBlocks;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \PHPCfg\Printer\Protobuf\Script\PBFunction\Block\Op\MapLabel $label
     *     @type array|\Google\Protobuf\Internal\MapField $childBlocks
     * }
     */
    public function __construct($data = NULL) {
        \PHPCfg\Printer\Protobuf\Specs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.protos.Script.Function.Block.Op.MapLabel label = 1;</code>
     * @return \PHPCfg\Printer\Protobuf\Script\PBFunction\Block\Op\MapLabel|null
     */
    public function getLabel()
    {
        return $this->label;
    }

    public function hasLabel()
    {
        return isset($this->label);
    }

    public function clearLabel()
    {
        unset($this->label);
    }

    /**
     * Generated from protobuf field <code>.protos.Script.Function.Block.Op.MapLabel label = 1;</code>
     * @param \PHPCfg\Printer\Protobuf\Script\PBFunction\Block\Op\MapLabel $var
     * @return $this
     */
    public function setLabel($var)
    {
        GPBUtil::checkMessage($var, \PHPCfg\Printer\Protobuf\Script\PBFunction\Block\Op\MapLabel::class);
        $this->label = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, uint32> childBlocks = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getChildBlocks()
    {
        return $this->childBlocks;
    }

    /**
     * Generated from protobuf field <code>map<string, uint32> childBlocks = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setChildBlocks($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->childBlocks = $arr;

        return $this;
    }

}

