<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lib/PHPCfg/Printer/Protobuf/specs.proto

namespace PHPCfg\Printer\Protobuf\Script\PBFunction;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>protos.Script.Function.Block</code>
 */
class Block extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .protos.Script.Function.Block.Op ops = 1;</code>
     */
    private $ops;
    /**
     * Generated from protobuf field <code>uint32 id = 2;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>repeated uint32 parentIds = 3;</code>
     */
    private $parentIds;
    /**
     * Generated from protobuf field <code>repeated .protos.Script.Function.Block.CatchTarget catchTargets = 4;</code>
     */
    private $catchTargets;
    /**
     * Generated from protobuf field <code>optional .protos.Script.Function.Block.FinallyTarget finallyTarget = 5;</code>
     */
    protected $finallyTarget = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \PHPCfg\Printer\Protobuf\Script\PBFunction\Block\Op[] $ops
     *     @type int $id
     *     @type int[] $parentIds
     *     @type \PHPCfg\Printer\Protobuf\Script\PBFunction\Block\CatchTarget[] $catchTargets
     *     @type \PHPCfg\Printer\Protobuf\Script\PBFunction\Block\FinallyTarget $finallyTarget
     * }
     */
    public function __construct($data = NULL) {
        \PHPCfg\Printer\Protobuf\Specs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .protos.Script.Function.Block.Op ops = 1;</code>
     * @return RepeatedField<\PHPCfg\Printer\Protobuf\Script\PBFunction\Block\Op>
     */
    public function getOps()
    {
        return $this->ops;
    }

    /**
     * Generated from protobuf field <code>repeated .protos.Script.Function.Block.Op ops = 1;</code>
     * @param \PHPCfg\Printer\Protobuf\Script\PBFunction\Block\Op[] $var
     * @return $this
     */
    public function setOps($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \PHPCfg\Printer\Protobuf\Script\PBFunction\Block\Op::class);
        $this->ops = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 id = 2;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint32 id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 parentIds = 3;</code>
     * @return RepeatedField<int>
     */
    public function getParentIds()
    {
        return $this->parentIds;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 parentIds = 3;</code>
     * @param int[] $var
     * @return $this
     */
    public function setParentIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->parentIds = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .protos.Script.Function.Block.CatchTarget catchTargets = 4;</code>
     * @return RepeatedField<\PHPCfg\Printer\Protobuf\Script\PBFunction\Block\CatchTarget>
     */
    public function getCatchTargets()
    {
        return $this->catchTargets;
    }

    /**
     * Generated from protobuf field <code>repeated .protos.Script.Function.Block.CatchTarget catchTargets = 4;</code>
     * @param \PHPCfg\Printer\Protobuf\Script\PBFunction\Block\CatchTarget[] $var
     * @return $this
     */
    public function setCatchTargets($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \PHPCfg\Printer\Protobuf\Script\PBFunction\Block\CatchTarget::class);
        $this->catchTargets = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .protos.Script.Function.Block.FinallyTarget finallyTarget = 5;</code>
     * @return \PHPCfg\Printer\Protobuf\Script\PBFunction\Block\FinallyTarget|null
     */
    public function getFinallyTarget()
    {
        return $this->finallyTarget;
    }

    public function hasFinallyTarget()
    {
        return isset($this->finallyTarget);
    }

    public function clearFinallyTarget()
    {
        unset($this->finallyTarget);
    }

    /**
     * Generated from protobuf field <code>optional .protos.Script.Function.Block.FinallyTarget finallyTarget = 5;</code>
     * @param \PHPCfg\Printer\Protobuf\Script\PBFunction\Block\FinallyTarget $var
     * @return $this
     */
    public function setFinallyTarget($var)
    {
        GPBUtil::checkMessage($var, \PHPCfg\Printer\Protobuf\Script\PBFunction\Block\FinallyTarget::class);
        $this->finallyTarget = $var;

        return $this;
    }

}

