<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lib/PHPCfg/Printer/Protobuf/specs.proto

namespace PHPCfg\Printer\Protobuf\Script;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protos.Script.Function</code>
 */
class PBFunction extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .protos.Script.Function.Block blocks = 1;</code>
     */
    private $blocks;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>optional string class = 3;</code>
     */
    protected $class = null;
    /**
     * Generated from protobuf field <code>string returnType = 4;</code>
     */
    protected $returnType = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\PHPCfg\Printer\Protobuf\Script\PBFunction\Block>|\Google\Protobuf\Internal\RepeatedField $blocks
     *     @type string $name
     *     @type string $class
     *     @type string $returnType
     * }
     */
    public function __construct($data = NULL) {
        \PHPCfg\Printer\Protobuf\Specs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .protos.Script.Function.Block blocks = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBlocks()
    {
        return $this->blocks;
    }

    /**
     * Generated from protobuf field <code>repeated .protos.Script.Function.Block blocks = 1;</code>
     * @param array<\PHPCfg\Printer\Protobuf\Script\PBFunction\Block>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBlocks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \PHPCfg\Printer\Protobuf\Script\PBFunction\Block::class);
        $this->blocks = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string class = 3;</code>
     * @return string
     */
    public function getClass()
    {
        return isset($this->class) ? $this->class : '';
    }

    public function hasClass()
    {
        return isset($this->class);
    }

    public function clearClass()
    {
        unset($this->class);
    }

    /**
     * Generated from protobuf field <code>optional string class = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setClass($var)
    {
        GPBUtil::checkString($var, True);
        $this->class = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string returnType = 4;</code>
     * @return string
     */
    public function getReturnType()
    {
        return $this->returnType;
    }

    /**
     * Generated from protobuf field <code>string returnType = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setReturnType($var)
    {
        GPBUtil::checkString($var, True);
        $this->returnType = $var;

        return $this;
    }

}

