<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lib/PHPCfg/Printer/Protobuf/specs.proto

namespace PHPCfg\Printer\Protobuf\Script\PBFunction\Block\Op;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protos.Script.Function.Block.Op.MapLabel</code>
 */
class MapLabel extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<string, .protos.Script.Function.Block.Op.OneLabelType> value = 1;</code>
     */
    private $value;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $value
     * }
     */
    public function __construct($data = NULL) {
        \PHPCfg\Printer\Protobuf\Specs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>map<string, .protos.Script.Function.Block.Op.OneLabelType> value = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>map<string, .protos.Script.Function.Block.Op.OneLabelType> value = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setValue($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \PHPCfg\Printer\Protobuf\Script\PBFunction\Block\Op\OneLabelType::class);
        $this->value = $arr;

        return $this;
    }

}

