<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lib/PHPCfg/Printer/Protobuf/specs.proto

namespace PHPCfg\Printer\Protobuf\Script\PBFunction\Block\Op;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protos.Script.Function.Block.Op.OneLabelType</code>
 */
class OneLabelType extends \Google\Protobuf\Internal\Message
{
    protected $value;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \PHPCfg\Printer\Protobuf\Script\PBFunction\Block\Op\MapLabel $map
     *     @type \PHPCfg\Printer\Protobuf\PrimitiveType $primitive
     *     @type \PHPCfg\Printer\Protobuf\Script\PBFunction\Block\Operand\OneOperand $operand
     * }
     */
    public function __construct($data = NULL) {
        \PHPCfg\Printer\Protobuf\Specs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.protos.Script.Function.Block.Op.MapLabel map = 1;</code>
     * @return \PHPCfg\Printer\Protobuf\Script\PBFunction\Block\Op\MapLabel|null
     */
    public function getMap()
    {
        return $this->readOneof(1);
    }

    public function hasMap()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.protos.Script.Function.Block.Op.MapLabel map = 1;</code>
     * @param \PHPCfg\Printer\Protobuf\Script\PBFunction\Block\Op\MapLabel $var
     * @return $this
     */
    public function setMap($var)
    {
        GPBUtil::checkMessage($var, \PHPCfg\Printer\Protobuf\Script\PBFunction\Block\Op\MapLabel::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protos.PrimitiveType primitive = 2;</code>
     * @return \PHPCfg\Printer\Protobuf\PrimitiveType|null
     */
    public function getPrimitive()
    {
        return $this->readOneof(2);
    }

    public function hasPrimitive()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.protos.PrimitiveType primitive = 2;</code>
     * @param \PHPCfg\Printer\Protobuf\PrimitiveType $var
     * @return $this
     */
    public function setPrimitive($var)
    {
        GPBUtil::checkMessage($var, \PHPCfg\Printer\Protobuf\PrimitiveType::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protos.Script.Function.Block.Operand.OneOperand operand = 3;</code>
     * @return \PHPCfg\Printer\Protobuf\Script\PBFunction\Block\Operand\OneOperand|null
     */
    public function getOperand()
    {
        return $this->readOneof(3);
    }

    public function hasOperand()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.protos.Script.Function.Block.Operand.OneOperand operand = 3;</code>
     * @param \PHPCfg\Printer\Protobuf\Script\PBFunction\Block\Operand\OneOperand $var
     * @return $this
     */
    public function setOperand($var)
    {
        GPBUtil::checkMessage($var, \PHPCfg\Printer\Protobuf\Script\PBFunction\Block\Operand\OneOperand::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getValue()
    {
        return $this->whichOneof("value");
    }

}

